version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.72
    steps:
      - checkout
      - run: cargo --version
      - run:
          name: Run Check
          command: "cargo install cargo-risczero && cargo risczero install && cargo check"