[package]
name = "ec-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"

# parsing
serde = { version = "1.0.147", default-features = false, features = ["derive"] }

[features]
default = ["std"]
std = [
  "serde/std",
]
